version: "3.8"

services:
    backend:
        image: 1222-back
        env_file: ./backend/.env

    frontend:
        image: 1222-front
        environment:
            - DANGEROUSLY_DISABLE_HOST_CHECK=true

    nginx:
        image: nginx
        ports:
            - 8080:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - frontend
            - backend
