name: Http health check

on:
  # schedule:
    # - cron:  '40 12 * * *'
  workflow_dispatch:
  
jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        id: check
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://ktatu-11-20.onrender.com
          max-attempts: 5
          retry-delay: 10s
      - name: Discord notification
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        if: always()
        with:
          severity: info
          description: Health check performed. Was ${{ steps.check.conclusion }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
